networks:
  yiipowered_public:
    name: yiipowered_public_php83
  yiipowered_private:
    name: yiipowered_private_php83

volumes:
  yiipowered_mysql_php83:
  php_socket_php83:

services:
  yiipowered:
    container_name: yiipowered_php83
    image: yiipowered:php8.3
    build:
      context: './'
      dockerfile: docker/php/Dockerfile-8.3
    volumes:
      - '.:/var/www'
      - 'php_socket_php83:/var/run/php'
    depends_on:
      - mysql
    networks:
      - yiipowered_private

  nginx:
    container_name: yiipowered_nginx_php83
    build:
      context: './docker/nginx'
    volumes:
      - './docker/nginx/local:/etc/nginx/conf.d:ro'
      - '.:/var/www'
      - 'php_socket_php83:/var/run/php'
    ports:
      - '8083:80'
    depends_on:
      - yiipowered
    networks:
      yiipowered_public:
        aliases:
          - yiipowered.test

  mysql:
    container_name: yiipowered_mysql_php83
    image: 'mariadb:10.1.44'
    ports:
      - '33063:3306'
    volumes:
      - yiipowered_mysql_php83:/var/lib/mysql/data
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yiipowered
    networks:
      - yiipowered_private
